### PR TITLE
possible fix on reformatting the slurp example

### PR DESCRIPTION
**Pull request by faraco**
* on doc site
   - https://docs.perl6.org/routine/slurp
- Since I don't know if this really 'fixing' it, I made this as a PR. Please suggests me changes to actually deal 
with this. Thanks.

best regards,
faraco.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Does it pass ``make xtest``? I'm thinking about [this one](https://github.com/perl6/doc/blob/master/xt/examples-compilation.t).

**Comment by faraco** [comment]
Should I add `:skip-test` attribute too?

**Comment by AlexDaniel** [comment]
Well, yes, or change the examples so that they pass.

**Comment by faraco** [comment]
Since my main goal is to fix the formatting first, I'll add the `:skip-test` for now.

**Comment by AlexDaniel** [comment]
Well, we will see how it goes. Thanks!

**Pull request merged**
