### PR TITLE
work around duplicate id= anchors

### PR DESCRIPTION
**Pull request by jsoref**
This should address  #631.

I'd rather someone else consider it (the output does change, it becomes wordier).

### CODE REVIEW

**Comment by AlexDaniel** [comment]
It has been a while since you submitted this pull request. What do you think about it now?

**Comment by AlexDaniel** [comment]
OK, so if one takes a look at https://github.com/perl6/doc/issues/561, it is easy to notice that duplicate anchors is the last big issue.

Therefore it is probably time to do something with this.

There are basically two options:

1. :+1: “Yes, let's fix the docs now!”
1. :-1: “No, we should fix it in ``Pod::To::HTML`` instead”… (or maybe change this pull request slightly?)

Below you can see before/after screenshots. It does become wordier, and it does introduce a bit of redundant information (the name of the class is displayed at least twice).

Also, “Any method” sounds really weird. I don't like it at all. Especially note these real cases:
* “Any method any”
* “Routine method multi”
* “Cool routine roots”
* “Any method end”

A bit funny sometimes, but we can probably live with that. Still, I think beginners will find it hard to read (or not? Am I the only one having troubles?), can we do something about it?

I am going to merge this if nobody dares to oppose, so **please speak up**.

By the way, it affects **all** pages. And that's for a good reason! For example, take a look at [IO::Handle#method_say](https://docs.perl6.org/type/IO$COLON$COLONHandle#method_say) – there are two methods “say” on that page, but the second link is broken because of duplicate ``id``s. So yeah, it makes sense.

----------

# Before
screenshot before

# After
screenshot after

**Comment by coke** [comment]
Perhaps instead of

Any method eager

use

(Any) method eager

**Comment by Altai-man** [comment]
The workaround is really small. When we'll fix our `Html::To::Pod`, it'll be super-easy to revert this back. So, generally, I'm +1 about this. But it is not a final solution.

We still have dead links at the `routine/` pages, it's my fault(or maybe not, since this part was completely broken, but just a little bit broken now because of me). I'll prepare a complete patch quickly(till today evening), so please, wait until it.

**Pull request merged**
