### PR TITLE
Added method sum() to Range pod

### PR DESCRIPTION
**Pull request by ahalbert**
#861

### CODE REVIEW

**Comment by Altai-man** [comment]
Seems good for me. Can you include the exact type of exception in the description, please? It can be useful.

**Comment by ahalbert** [comment]
The exception is thrown in NQP, so would that be documented in Perl6? 

The error:
Cannot convert string to number: base-10 number must begin with valid digits or '.' in '⏏a' (indicated by ⏏)
  in any call_with_capture at gen/moar/m-Metamodel.nqp line 3865
  in block <unit> at <unknown file> line 1

**Comment by jonathanstowe** [comment]
Well it's ```X::Str::Numeric``` that is thrown and it is defined in the Exception.pm so yes arguably it should be documented.  I'm minded to merge this and then fix that immediately afterward.

**Comment by ahalbert** [comment]
I've added the missing exception. It is rebased into the last commit.

**Comment by jonathanstowe** [comment]
If I get a minute I'll add a document for the exception itself.

**Pull request merged**
