### PR TITLE
More documentation on library paths and names

### PR DESCRIPTION
**Pull request by Kaiepi**
## The problem
Library paths and names needed more documentation. See https://github.com/perl6/doc/issues/1513

## Solution provided
More was written

### CODE REVIEW

**Comment by Skarsnik** [comment]
This example is misleading. the function does what specify the ABI version to the native trait is supposed to do, and people SHOULD always specify an ABI version (very few execption like libmysqlclient ><)

**Comment by Kaiepi** [comment]
Updated

**Comment by Skarsnik** [comment]
No, I mean the content of the function itself. The example was correct previously, it's just we should not encourage users to do what the ABI version does already :)

**Comment by Kaiepi** [comment]
You mean like returning `/usr/local/lib/ebar/bar`?

**Comment by Skarsnik** [comment]
Just read the https://docs.perl6.org/language/nativecall#ABI/API_Version
If I write
`is native('bar', 'v1)` it should give you /usr/lib/libbar.so.1 on openbsd (/usr/lib/ will be the default system library path, (I think NC/moar query ld config).) If it's not the case it should be patched in NC or Moar to follow the proper OpenBSD intended behavior.

But what I mean is users should be encouraged to use the ABI version argument. Giving the user an example of the use of the Routine argument type witch does what the API feature does is probably a bad idea/misleading. Maybe a better example could be just a function that call pkg-config to get the path (or something similar)

**Comment by Skarsnik** [comment]
Thank :)

**Pull request merged**
