### PR TITLE
define the code point properties in the description

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
>  C<Zl> ((Separator, line)

Two ``((`` here ↑.

Also, it seems like **Lm** is not mentioned.

Example:
```perl
my $ʹ = 42; say $ʹ    # prints 42
say ‘ʹ’.uniprop;      # prints Lm
say ‘ʹ’.uniname;      # prints MODIFIER LETTER PRIME
```

**Comment by tbrowder** [comment]
Alex, all your comments have been addressed--thanks!

**Comment by AlexDaniel** [comment]
>  Any codepoint with the C<Lo> (Letter, other) property can be used as an alphabetic where case distinctions do not matter.

↑ Does anybody know when case matters? Or what kind of “case distinctions” is it talking about?
Should we group **Lm** with **Lu** and **Ll** or with **Lo**?

> (These aren't decimal digit characters, so can't be combined.)

↑ I think that it does not make it clear enough that unicode digit characters can be combined. Perhaps it could be rephrased a bit?

Or maybe we can throw in some examples? Like:
```perl6
say ١٩   # prints 19
```

**Comment by tbrowder** [comment]
Okay with merging what we have at the moment?  I can try to add something for your consideration on the next pull request.

**Comment by AlexDaniel** [comment]
Of course!

**Pull request merged**
