### PR TITLE
doc translation for Chinese

### PR DESCRIPTION
**Pull request by bollwarm**
## the  addition files 
5to6-nutshell.zh.pod6  5to6-perlfunc.zh.pod6  5to6-perlsyn.zh.pod6  faq.zh.pod6
5to6-overview.zh.pod6  5to6-perlop.zh.pod6    5to6-perlvar.zh.pod6  rb-nutshell.zh.pod6

##  Description
The completed  contents list:
5to6-overview.pod6
5to6-nutshell.pod6
5to6-perlfunc.pod6
5to6-perlop.pod6
5to6-perlsyn.pod6
5to6-perlvar.pod6
faq.pod6
rb-nutshell.pod6

ALL these files are synced to the newest and translate to the Chinese language ,and be added in the `resources/i18n/zh/doc
/Language/` with the  names xxx.zh.pod6

### CODE REVIEW

**Comment by JJ** [comment]
I already closed this pull request. We will not admit translation of documentation pages into this repository. Please publish them as a separate repository.

**Comment by JJ** [comment]
Please read [my comment to the other PR for the reasons why this has been closed](https://github.com/perl6/doc/pull/2194#issuecomment-418982608). Once again, we are very grateful for your work and we think it's a valuable addition to the Perl 6 documentation. Only we can't admit it in this repository.

**Comment by bollwarm** [comment]
This reo add the `resources/i18n/` just for a README.zh.cn ???? 
or
Maybe I understand something wrong！

**Comment by JJ** [comment]
It includes 91 commits and 8 changed files. It's better if you start with a fresh clone of the repo and add that file before creating a new pull request.

**Pull request closed without merging**
