### PR TITLE
minor typo edit

### PR DESCRIPTION
**Pull request by molecules**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Such minor things you can just commit directly to master. I believe you have the correct access permissions to do so.

**Comment by molecules** [comment]
I don't think that I have write access. If I do, its not obvious to me how to commit this pull request.

**Comment by zoffixznet** [comment]
I mentioned it to the admins to take a look at your privs. Thanks.

**Comment by molecules** [comment]
Thanks!

**Pull request merged**
