### PR TITLE
The translation for Chinese

### PR DESCRIPTION
**Pull request by bollwarm**
## The translation for Chinese of the lists 👍 

5to6-nutshell.pod6
5to6-perlfunc.pod6
5to6-perlop.pod6
5to6-perlsyn.pod6
5to6-perlvar.pod6
faq.pod6
rb-nutshell.pod6

##  Description
The Perl 6 version Translate in the doc/Lanages with the prefix cnXXXX ，cn standing the Chinese:

all complated files list are at this time:

5to6-nutshell.pod6
5to6-perlfunc.pod6
5to6-perlop.pod6
5to6-perlsyn.pod6
5to6-perlvar.pod6
faq.pod6
rb-nutshell.pod6

and addition markdown version for github showing at the cndoc dir: cnXXXX.md

and a Chinese README is CNREADME.md.

I will sync with https://github.com/perl6/doc for news contents and more files !

### CODE REVIEW

**Comment by tbrowder** [comment]
Great work, thanks!

With the doc reorg we need to determine the proper location for the Language files to allow multiple language translations.

**Comment by JJ** [comment]
Neither I am sure about the correct location of the translated 5to6 docs, or, for that matter, if those translations should actually go into this repository. Take into account this is installed with every copy out there. Can we please discuss this a bit, here and/or in the IRC channel, before we merge?

**Comment by TisonShadowsong** [comment]
I assign myself to this pr and would monitor its process. wish we be able to make i18n of perl6/doc available as soon as possible. cheers!

**Comment by coke** [comment]
In addition to deciding where in the repository these files should go, I think we also need some kind of consensus on what the UI is going to be for the user of the website to switch to Chinese, does this impact the site generation etc.

**Comment by JJ** [comment]
El sáb., 21 jul. 2018 a las 1:15, Will Coleda (<notifications@github.com>)
escribió:

> In addition to deciding where in the repository these files should go, I
> think we also need some kind of consensus on what the UI is going to be for
> the user of the website to switch to Chinese, does this impact the site
> generation etc.
>

I have an answer for that: *outside* the repository. While this repository
is more than just a bunch of pod files, so there's value adding
translations to this, the issues you mention are major. Do we want to
support and maintain partial translations of a few pages? Do we want to
include switching languages into the (already complex) site building tools?

Translating is not just a matter of taking words from one part and putting
them into another. You have to add lots of professional tools for doing it,
including terminology, patterns translations, and so on. perl5 does have
that, at least in Spanish, but I don't see that happening here.

So I'm for not accepting the PR

**Comment by bollwarm** [comment]
The CNREADME  we  can ignore it ，it is a translate of README  and is an index for Chinese version  .md files in CNDOC dir. The main Translations  are  doc/Languages dir:

cn5to6-nutshell.pod6   
cn5to6-perlfunc.pod6
cn5to6-perlop.pod6
cn5to6-perlsyn.pod6
cn5to6-perlvar.pod6
cnfaq.pod6
cnrb-nutshell.pod6

and the format is the same as the origin .pod6 files and the names can be changed as
5to6-nutshell.cn.pod6  or

Can be a new dir, but this Url like may be a qusetion。

AND 

I will translate continuity   to synchronize the update of this repo for these files

**Comment by JJ** [comment]
I really thank you for all your work, but I don't think these translations belong in the same repository. Main reason is that this is the official documentation for the language, and including translations (other than the READMEs) would make everyone download all translated pages when they install it. We don't have any kind of plan for maintaining search using p6doc on the translations, or, for that matter, maintaining the translation of translated documents. We would very much prefer to keep a link to translated (partial) documentation here, and once again we are very grateful that you took the job of doing the translation. So I think I'm closing this pull request.

**Pull request closed without merging**
