### PR TITLE
Adds definition for Repository

### PR DESCRIPTION
**Pull request by JJ**
it's not in the TODO list, but it simply wasn't there, so I said, why not...

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks.

**Comment by JJ** [comment]
Thanks. I've seen a bunch of other terms I could have a go at. Is it better
to mark them as TODO and then proceed, or should I define them directly?

**Comment by zoffixznet** [comment]
Just commit them directly.

**Comment by JJ** [comment]
:+1:

**Pull request merged**
