### PR TITLE
Update regexes.pod

### PR DESCRIPTION
**Pull request by edehont**
I found a small typo: staring -> starting

### CODE REVIEW

**Comment by zaucker** [comment]
Thanks!

**Comment by edehont** [comment]
You're welcome.
It's my first contribution to a project on GitHub, so I hope I did everything as I'm supposed to.

**Comment by zaucker** [comment]
Perfectly ... :-)

Am 14. Februar 2016 17:38:25 MEZ, schrieb Eric de Hont <notifications@github.com>:
>You're welcome.
>It's my first contribution to a project on GitHub, so I hope I did
>everything as I'm supposed to.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/perl6/doc/pull/395#issuecomment-183918257

--
Fritz Zaucker
Oetiker+Partner AG
Aarweg 15
CH-4600 Olten
+41 62 775 9903

**Comment by edehont** [comment]
In that case, expect more pull requests ;-)

**Comment by moritz** [comment]
@edehont or accept the invitation I just sent you, and push directly :-)

**Comment by edehont** [comment]
Nice, thanks!

I have accepted, of course.

Eric de Hont

Op 15-02-16 om 13:27 schreef Moritz Lenz:

**Pull request merged**
