### PR TITLE
m/ / and / / examples added

### PR DESCRIPTION
**Pull request by COMBORICO**
Added examples to help illustrate difference between m/ / and / /.  Zoffix provided the examples.  I provided the learning.  An example for rx/ / is needed.  As a newbie, this info is very helpful and rare.  It is not in Think Perl 6, ttbomk.  And definitely not in Perl6Intro.com.  Needed info or something better.

### CODE REVIEW

**Comment by zoffixznet** [comment]
👍 Thanks!

**Comment by JJ** [comment]
Thanks. Do you mean that, additionally, an example for `rx//`is needed?

**Comment by COMBORICO** [comment]
JJ, yes.

**Comment by JJ** [comment]
@COMBORICO please open an issue for that...

**Pull request merged**
