### PR TITLE
Css-based TOC animation

### PR DESCRIPTION
**Pull request by Altai-man**
Smooth css animation for TOC. This animation isn't based on (max-)height. The only JS part needed is to change css classes, should work with most browsers.

### CODE REVIEW

**Comment by Altai-man** [comment]
Fixes https://github.com/perl6/doc/issues/686

**Comment by Altai-man** [comment]
We still need two classes for animation, since if we remove one, hiding or showing will be without animation transition.

**Comment by AlexDaniel** [comment]
But, but… it does not work at all! It seems like .css file was not generated or something.

**Comment by Altai-man** [comment]
It was fixed. I thought the server builds sass-files by itself.

**Comment by zoffixznet** [comment]
@AlexDaniel which browser?

In my Firefox the failure modes are:

1. The text disappears, but the height of the table is still there, so the point of hiding the ToC is gone; I still have to scroll (this is on small-width view, where the ToC is at the top of the page)
2. After I hide the ToC, on page load the ToC flashes in shown position and then animates to an off position. It should start off in off position
3. FWIW, the animation no longer works on my phone in Opera browser. It's not one of our supported browsers, I know, but still... :crying_cat_face:

**Comment by zoffixznet** [comment]
> It was fixed. I thought the server builds sass-files by itself.

Not yet. It just uses the generated `html/css/style.css` file.

**Comment by coke** [comment]
I have the same issue as @zoffixznet - the text hides, but the vertical space it consumes is still there, and the default on page reload is wrong.

Please revert this for now.

**Comment by Altai-man** [comment]
Reverted. I suppose, we should just remove animation at all then.

**Pull request merged**
