### PR TITLE
Add whitespace and reflow

### PR DESCRIPTION
**Pull request by uzluisf**

### CODE REVIEW

**Comment by uzluisf** [comment]
A newest commit seems to have taken care of what this commit was trying to fix except for the text reflow. I guess it depends on the keyboard but is there an easy way to type in that character?

**Comment by JJ** [comment]
@uzluisf there's a plugin for Atom that makes it easy, or just the average keyboard input in emacs. There's probably some way in other editors...

**Comment by coke** [comment]
in vim, when in insert mode: control-k space space

**Comment by uzluisf** [comment]
@JJ @coke Thanks for the suggestion! The vim command will do.

**Pull request closed without merging**
