### PR TITLE
Now we take predefined search values from outer file

### PR DESCRIPTION
**Pull request by Altai-man**
Plain text file because it's universal for all.

I've left js syntax here, because it's easy and we don't have to do anything else with source file.

I want opinions about - is it needed to change file to some format and then parse it in `htmlify`(if someone hates piece of js code in some outer file)? Maybe like this:
```
Category
Value
Url

Category
...
```
it is quite easy file format and I can implement this.

Ability to make links that point to just pages, not anchors, is quite good for search, for example, see https://github.com/perl6/doc/issues/724

### CODE REVIEW

**Comment by zoffixznet** [comment]
Personally I'm :-1: on having a human-generated list of search terms. Content changes and pages get deleted. This PR introduces another maintenance burden that we need to keep `predefined-search-items` up to date and accurate. 

Is there no way to use the `X<>` POD marker to generate these search terms?

**Comment by Altai-man** [comment]
@zoffixznet, afaik - no. But I'm not a pod6 magician, of course, so I can be wrong.

The thing is, we already have two hardcoded entries in js-code. I just provided an easier way to update them.
cast @AlexDaniel, @gfldex.

**Comment by zoffixznet** [comment]
> The thing is, we already have two hardcoded entries in js-code. I just provided an easier way to update them.

Ah, my bad. I missed that. It'd be best if we didn't have those, but if there's no way then there's no way.

**Comment by AlexDaniel** [comment]
I like it.

We can have a discussion about whether we should have manually defined items or not, but we already do, so… Basically I see no reasons not to merge.

The only thing is that people will now be tempted to add search items manually (given that now it is slightly easier). But that's OK, once there is a way to get rid of this file we will do it, but right now let's improve the search.

**Pull request merged**
