### PR TITLE
Remove some unneeded unspace

### PR DESCRIPTION
**Pull request by awwaiid**
(I hate unspace)

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks a lot!

**Comment by awwaiid** [comment]
mmm... it may not have been a good idea to merge this so quickly :) . I'm checking that I didn't break anything now...

**Comment by zoffixznet** [comment]
Sorry, I jumped the gun :)

It does seem [this line](https://github.com/perl6/doc/pull/251/files#diff-16f2390767c1219dc1e184afbec86235R587) now [breaks the build](https://travis-ci.org/perl6/doc#L1607). I think it's the same issue as when a hyper op is used with a method chain on multiple line you get errors too...

**Comment by zoffixznet** [comment]
Hm... I reverted that part, but it's still failing. no idea why

**Pull request merged**
