### PR TITLE
new test for generated html files

### PR DESCRIPTION
**Pull request by finanalyst**
## The problem
When all the html files have been generated, all the `<a href="somelink">...</a>` should point to valid targets.

Currently, this does not happen because of bugs in the current tool-chain, particularly htmlify. 

Although, it is also possible to test whether each link in the source Pod6 file, namely each `L< >` is valid, this does not guarantee that the final html file generated to render the Pod6 source has correct links. In fact, currently, the html files contain approximately 120 incorrect links.

## Solution provided
A test file `verify-generated-html-link.t` goes through each html file in the html directory, finds each `<a` link and then verifies if the link exists (a) against a live static file server defined in P6_DOC_TEST_SERVER or (b) against the html files in the html directory.

The test uses 16 threads, and TAP syntax errors may occur when tests are returned in a different order.

### CODE REVIEW

**Comment by coke** [comment]
See #1433

**Comment by coke** [comment]
When I run this locally with no args, it runs about a 100 tests (104, 105, 91, then 97), hangs for a bit, then ends reporting a few failures.

**Comment by coke** [comment]
Also, fails https://raw.githubusercontent.com/perl6/mu/master/misc/camelia.txt, but that is responding with content.

**Comment by JJ** [comment]
We are finally developing a minimal set of documents for testing in a separate repo as part of Google Summer of Code. Thanks a lot.

**Pull request closed without merging**
