### PR TITLE
A basic start to documenting IPC

### PR DESCRIPTION
**Pull request by zostay**
I started a basic document for `run`, `shell`, `Proc`, and `Proc::Async`. It needs proofreading and to be fleshed out further.

Needs to be added: signal handling, maybe more about pipes, IO::Socket, IO::Socket::INET, etc.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I like it. But this line does not work:
```perl6
         my ($sha, $subject) = $line.split: / /;
```
should be this, I think:
```perl6
         my ($sha, $subject) = $line.split: /‘ ’/, 2;
```

> provides access using asynchronous L<Supply|/type/Supply>s.

Supplys?

**Comment by jonathanstowe** [comment]
I'm going to merge, a visible page gets more patches :)

**Comment by tommystanton** [comment]
Good stuff!  Having the text `IPC` somewhere would probably be good too though.

**Comment by zostay** [comment]
Picky. Picky.

**Pull request merged**
