### PR TITLE
use a code block for options until the p6 pod table bug is fixed

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by zoffixznet** [comment]
:-1: I'm working on fixing this bug ATM.

**Comment by tbrowder** [comment]
On Mon, Jun 20, 2016 at 7:49 PM, Zoffix Znet <notifications@github.com> wrote:
> I'm working on fixing this bug ATM.

I've discussed the bug with Patrick Michaud here at TPC::NA::2016, and
he will help me debug it.  Shall I stop my efforts?

-Tom

P.S.  I still think the PR should go ahead--no telling how long the
fix will take.  And my temp fix is usable and better looking without
the backslashes.

**Comment by zoffixznet** [comment]
> Shall I stop my efforts?

No, @pmichaud's help would be appreciated. I'm well out of my depth. Please work with Patrick to try to rectify this.

Here's how far I got and the issues I'm still facing:

#### 1.

I managed to fix the original [RT#128221](https://rt.perl.org/Ticket/Display.html?id=128221) with the following changes, but the fix is not enough (note: just the first change may be all that's needed):

```diff
zoffix@VirtualBox:~/CPANPRC/rakudo$ gd
diff --git a/src/Perl6/Pod.nqp b/src/Perl6/Pod.nqp
index 5e19e83..e04a657 100644
--- a/src/Perl6/Pod.nqp
+++ b/src/Perl6/Pod.nqp
@@ -279,8 +279,12 @@ class Perl6::Pod {
         $i := 0;
         while $i < +@rows {
             my $v := @rows[$i];
-            if $v ~~ /^'='+ || ^'-'+ || ^'_'+ || ^\h*$/ {
+            if $v ~~ /^
+                [ <[=\h+|]>+ | <[-\h+|]>+ | <[_\h+|]>+ | <[\h+|]>+ ]
+            $/ {
                 @res[$i] := $v;
+                print($i);
+                print($v);
             } elsif $v ~~ /\h'|'\h/ {
                 my $m := $v ~~ /
                     :ratchet
@@ -409,7 +413,9 @@ class Perl6::Pod {
 
         my $i := 0;
         while $i < +@rows {
-            unless @rows[$i] ~~ /^'='+ || ^'-'+ || ^'_'+ || ^\h*$ / {
+            unless @rows[$i] ~~ /^
+                [ <[=\h+|]>+ | <[-\h+|]>+ | <[_\h+|]>+ | <[\h+|]>+ ]
+            $/ {
                 my @line := nqp::split('', @rows[$i]);
                 my $j := 0;
                 while $j < +@line {
@@ -459,7 +465,9 @@ class Perl6::Pod {
 
         my @ret := [];
         for @rows -> $row {
-            if $row ~~ /^'='+ || ^'-'+ || ^'_'+ || ^\h*$/ {
+            if $row ~~ /^
+                [ <[=\h+|]>+ | <[-\h+|]>+ | <[_\h+|]>+ | <[\h+|]>+ ]
+            $/ {
                 @ret.push($row);
                 next;
             }
zoffix@VirtualBox:~/CPANPRC/rakudo$ 
```

#### 2.

However, the [test in roast](https://github.com/perl6/roast/blob/master/S26-documentation/07-tables.t#L140) for this bug is poor. Here's my version:

```perl6
=begin table
-Col 1 | -Col 2 | _Col 3 | =Col 4
=======+========+========+=======
Col 1  | -Col 2 | _Col 3 | =Col 4
-------|--------|--------|-------
Col 1  | -Col 2 | _Col 3 | =Col 4
Col 1  | -Col 2 | _Col 3 | =Col 4
 Col 1 | -Col 2 | _Col 3 | =Col 4
Col 1  | -Col 2 | _Col 3 | =Col 4
Col 1  | -Col 2 | _Col 3 | =Col 4
-------|--------|--------|-------
Col  1 | Col 2  |  Col 3 |  Col 4
=end table
```

And it parses like this. As you can see the columns' contents are broken:

```perl6
headers =>
["Col 1", "-Col 2", "_Col 3", "=Col 4"],

contents => [
    ["ol 1", "-Col 2", "_Col 3", "=Col 4"],
    [
        "ol 1 ol 1 Col 1 ol 1 ol 1",
        "-Col 2 -Col 2 -Col 2 -Col 2 -Col 2",
        "_Col 3 _Col 3 _Col 3 _Col 3 _Col 3",
        "=Col 4 =Col 4 =Col 4 =Col 4 =Col 4"
    ],
    ["ol 1", "Col 2", "Col 3", "Col 4"]
]
```

If you and pmchaud can fix this, that would be great :) Thanks.

**Comment by tbrowder** [comment]
On Monday, June 20, 2016, Zoffix Znet <notifications@github.com> wrote:

> Shall I stop my efforts?
>
> No, @pmichaud <https://github.com/pmichaud>'s help would be appreciated.
> I'm well out of my depth. Please work with Patrick to try to rectify this.
>
> Here's how far I got and the issues I'm still facing:
>

Looks like you've made a great start!  Do you have Patrick's e-mail address?

 -Tom

>

**Pull request merged**
