### PR TITLE
Add package (namespace) documentation, taken from S02

### PR DESCRIPTION
**Pull request by awwaiid**
Looking at #178, I realized we have basically nothing about package namespaces spelled out. I found some material in S02 and started to chop it down -- this is my first pass. We can merge it as "better than nothing" if we like. I'll continue refining in any case.

Mostly I'd like feedback about WHERE are some good places to put this info. Language/modules was the first place I hit upon, but I also considered Language/packages as possibly it's own document.

### CODE REVIEW

**Comment by LLFourn** [comment]
mmm yeah I suggest "packages and namespaces" as a new .pod file. Writing modules is not the same as understanding packages and namespaces in p6 so I don't think it belongs in modules.pod.

:+1:  for new file

**Comment by LLFourn** [comment]
`import` might be a nice thing to explain on this new page. Just had someone in irc looking for import and not finding it in the docs.

**Comment by awwaiid** [comment]
@LLFourn if this is tollerable I'd like to merge it where it is and then incrementally improve it

**Comment by jonathanstowe** [comment]
Yeah' I'll go with merging it now.  If people can see it they'll be more inclined to suggest improvements.

**Pull request merged**
