### PR TITLE
Attempt to explain ways to declare return type in signature

### PR DESCRIPTION
**Pull request by Altai-man**
Review of grammar is welcome!

Attempt to fix https://github.com/perl6/doc/issues/1027

### CODE REVIEW

**Comment by Altai-man** [comment]
@tbrowder, I commit mostly index/examples-related stuff that doesn't require strong English skills(because I'm really bad with English, obviously) and I intentionally don't "write" any documentation for that reason - it will be low-quality.
But I still picked up this issue, so I really appreciate your help in pointing out my silly mistakes, since native speaker review is always a great help. Don't hesitate to review!

**Comment by AlexDaniel** [comment]
I think the text should suggest that ``-->`` should be preferred.

**Comment by tbrowder** [comment]
On Sat, Dec 10, 2016 at 11:36 AM, Altai-man <notifications@github.com> wrote:
> @tbrowder, I commit mostly index/examples-related stuff that doesn't require
> strong English skills(because I'm really bad with English, obviously) and I
> intentionally don't "write" any documentation for that reason - it will be
> low-quality.
> But I still picked up this issue, so I really appreciate your help in
> pointing out my silly mistakes, since native speaker review is always a
> great help. Don't hesitate to review!

Will do--glad to help!  I just made another tweak after your last commit.

Best regards,

-Tom

**Comment by Altai-man** [comment]
I squashed the latest three commits into one for a prettier history.
I'm not sure, is it enough to just write "preferred"? Reasons like "It is easier to parse" or "6.d" don't seem for me like a good reasons to the reader.

**Comment by tbrowder** [comment]
Merge and press on.

**Pull request merged**
