### PR TITLE
Style updates to faq and about pod.

### PR DESCRIPTION
**Pull request by antquinonez**

### CODE REVIEW

**Comment by coke** [comment]
Nit:

+There's also modules in the ecosystem to do this,

is wrong. It's there are, not there is.

**Comment by coke** [comment]
This merge fails 'make xtest' 👎

**Comment by coke** [comment]
+=item Junctions allowing easy checking of multiple possibilities; e.g., $a == 1|3|42 ( is $a equal to 1 or 3 or 42 ?).

This changes the meaning of the original sentence. It really is one or the other, and not asking a question.

**Comment by coke** [comment]
Lots of changes just to line breaks in source: 👎

**Comment by antquinonez** [comment]
@coke I can 
--remove the ? in is $a equal to 1 or 3 or 42 ?
-- I can make it so There's doesn't stand in for there are (http://english.stackexchange.com/questions/77089/there-s-or-there-are says it's okay. That's how I read it but I'll make the change )

Question: Don't you think good POD needs some line breaks? The section toward the end of faq.pod6 didn't make proper use of line breaks.

And another question. How do I run this make xtest and what seems to be the problem? I read the guide to contributing to the project and couldn't understand what the steps were to running the tests.

**Comment by coke** [comment]
(line breaks) maybe? We don't have a policy on that, and mixing this in with the language style updates makes it harder to verify you haven't changed anything in those sections.

(how to run make xtest) https://github.com/perl6/doc/blob/master/CONTRIBUTING.md#running-tests

You can run them with:
```
make xtest
```

It's not mandatory but is very nice to have for PRs.

**Comment by antquinonez** [comment]
@coke, I'll remove the line breaks.
I'll take another look at that 'make xtest'. 
Thanks

**Comment by antquinonez** [comment]
I think I've made all the requested changes/fixes. Also, ran 'make xtest' and fixed issues it identified.

**Comment by coke** [comment]
thanks!

**Pull request merged**
