### PR TITLE
Add minor fixes, rephrase sentences and reflow text

### PR DESCRIPTION
**Pull request by uzluisf**

### CODE REVIEW

**Comment by zoffixznet** [comment]
FWIW: you have a commit bit and can just commit all this stuff directly.

**Comment by uzluisf** [comment]
I know but I'd rather have someone else review it so as to avoid reckless merges.

**Comment by zoffixznet** [comment]
There's always `git revert` 😉

**Comment by uzluisf** [comment]
Thanks, @zoffixznet !

**Pull request merged**
