### PR TITLE
Converted -- to –

### PR DESCRIPTION
**Pull request by ahalbert**
See #888 
Is it important if code chunks also use – instead of --? I'll go back and change that if so.

### CODE REVIEW

**Comment by ahalbert** [comment]
It fails this in the CI: what does this mean?
```
pod2onepage --threads=1 -v --source-path=./doc --exclude=404.pod6,/.git,/precompiled > html/perl6.xhtml

Type check failed in binding to $id; expected CompUnit::PrecompilationId but got Str ("4CDC84469EF12631D41D...)

  in block  at /home/travis/.rakudobrew/moar-nom/install/share/perl6/site/resources/5E2F5C8269024A43AAC8425E863FC9AD6F5D0B0C line 66

  in sub parse-pod-file at /home/travis/.rakudobrew/moar-nom/install/share/perl6/site/resources/5E2F5C8269024A43AAC8425E863FC9AD6F5D0B0C line 59
  in block  at /home/travis/.rakudobrew/moar-nom/install/share/perl6/site/resources/5E2F5C8269024A43AAC8425E863FC9AD6F5D0B0C line 38

  in sub MAIN at /home/travis/.rakudobrew/moar-nom/install/share/perl6/site/resources/5E2F5C8269024A43AAC8425E863FC9AD6F5D0B0C line 38

  in block <unit> at /home/travis/.rakudobrew/moar-nom/install/share/perl6/site/resources/5E2F5C8269024A43AAC8425E863FC9AD6F5D0B0C line 54
```

**Comment by AlexDaniel** [comment]
> Is it important if code chunks also use – instead of --?

What kind of code chunks? I did a quick grep but did not find anything relevant to what you are mentioning. Can you show some examples?

**Comment by ahalbert** [comment]
An example is 

```
    proto congratulate(Str $reason, Str $name, |) {*}
    multi congratulate($reason, $name) {
       say "Hooray for your $reason, $name";
    }
    multi congratulate($reason, $name, Int $rank) {
       say "Hooray for your $reason, $name -- got rank $rank!";
    }
```
in functions.pod6

**Comment by AlexDaniel** [comment]
@ahalbert I think that an argument can be made both ways, so just leave it as is. It really does not matter that much if you're using monospace font, and I think that most people do.

**Pull request merged**
