### PR TITLE
Allow fuzzy searching

### PR DESCRIPTION
**Pull request by coke**
For #999

### CODE REVIEW

**Comment by coke** [comment]
Grabbed a small levenshtein function, and overrode the search filter to use that. Only tested basic searching, I'm sure there are things that used to be found that aren't now. let me know, easy enough to fix.

**Comment by zoffixznet** [comment]
Merge conflict is due to https://github.com/perl6/doc/commit/b7f0e9de59291320b60bcdf87b0203acd6edd91a

**Comment by coke** [comment]
force pushed a rebase without a conflict.

**Comment by zoffixznet** [comment]
Thanks.

**Pull request merged**
