### PR TITLE
Add an index for ;;

### LINKED ISSUE #841: ;; is not searchable
In roast, `;;` is used here
https://github.com/perl6/roast/blob/master/S06-multi/syntax.t#L38-L53

In the perl 6 document, the description of the `;;` is in the following page
https://docs.perl6.org/type/Signature#Long_Names

### PR DESCRIPTION
**Pull request by titsuki**
Fix #841

### CODE REVIEW

**Comment by Altai-man** [comment]
Thanks for the noticing.
I have suspicious that pointing straight to the header will be better here. I'll do a quick test now...

**Comment by titsuki** [comment]
@Altai-man hmm... I think so too, but we have a CI environment and there's no restrictions not to leverage it.

**Comment by titsuki** [comment]
ok I'll merge this PR :)

**Comment by Altai-man** [comment]
If it works then I'm okay, but the style is somewhat different comparing to two nearest paragraphs. Anyway, I can't really work on the vacation, so let it be.
Thanks for your contribution!

**Comment by titsuki** [comment]
oh... It seems broken
https://docs.perl6.org/type/Signature#Long_Names

**Pull request merged**
