### PR TITLE
Perl6 docs

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks a lot!

**Comment by AlexDaniel** [comment]
It looks like there are a couple of formatting issues. [See yourself](http://doc.perl6.org/programs/00-running). But that's okay, these can be fixed as we go. Generally I really like the idea of having these pages.

**Comment by tbrowder** [comment]
On Sat, Jun 18, 2016 at 12:49 PM, Zoffix Znet <notifications@github.com> wrote:
> Thanks a lot!

My pleasure--sorry it took so long.  As you can see, there are issues,
but I hope experts can cure them.

**Comment by AlexDaniel** [comment]
Looking at it again, are we sure that we want a separate “Programs” tab? Can't we have these things as part of the “Language” page?

**Comment by tbrowder** [comment]
On Sat, Jun 18, 2016 at 6:59 PM, Aleks-Daniel Jakimenko-Aleksejev
<notifications@github.com> wrote:
> Looking at it again, are we sure that we want a separate “Programs” tab?
> Can't we have these things as part of the “Language” page?

I think Zoffix agrees that the separate tab is friendlier to new
folks.  And executables don't really fit in Language.

**Comment by zoffixznet** [comment]
Yeah, there's plenty of space for it.`Language` is overcrowded as it is. Maybe some things can be moved out of it and into `Programs`, like http://docs.perl6.org/language/modules-extra

**Pull request merged**
