### PR TITLE
Update 5to6-nutshell.pod6 (mentioned AUTOLOAD/FALLBACK)

### PR DESCRIPTION
**Pull request by holli-holzer**
mentioned AUTOLOAD/FALLBACK

### CODE REVIEW

**Comment by W4anD0eR96** [comment]
@zoffixznet could you please check this PR? I know little about Perl 5.

**Comment by zoffixznet** [comment]
👍 Thanks!

**Comment by holli-holzer** [comment]
The link is broken, doubly base 64 encoded or someting

**Comment by zoffixznet** [comment]
> The link is broken, doubly base 64 encoded or someting

https://github.com/perl6/doc/commit/2ca01283238a789e1ca7882580b3238ef6af5992 probably worksaround that

**Comment by zoffixznet** [comment]
@holli-holzer I sent you an invite to **perl6** GitHub org. You can accept it on https://github.com/perl6/ and it'll gives you access to most of our repos, so you can commit directly.

**Pull request merged**
