### PR TITLE
Describe $*MAIN-ALLOW-NAMED-ANYWHERE

### PR DESCRIPTION
**Pull request by ufobat**

### CODE REVIEW

**Comment by ufobat** [comment]
But it is working and people are probably using it since this talk: https://youtu.be/D16wa-gnFwE?t=802

**Comment by AlexDaniel** [comment]
@ufobat that's right. Can you open an issue in https://github.com/perl6/roast/issues?

**Comment by zoffixznet** [comment]
> But it is working and people are probably using it since this talk

That doesn't make it part of the language.

**Comment by stmuk** [comment]
On 29 June 2017 at 13:25, Zoffix Znet <notifications@github.com> wrote:

> But it is working and people are probably using it since this talk
>
> That doesn't make it part of the language.
>
Is there somewhere things like this, part of the rakudo implementation, but
not tested and not part of the spec can be documented?


-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by AlexDaniel** [comment]
@stmuk I don't think I understand your question. But here are some relevant links:
* [What should we do with notspecced things?](https://github.com/perl6/doc/issues/835)
* [NOTSPECCED issues](https://github.com/perl6/doc/issues?utf8=%E2%9C%93&q=label%3ANOTSPECCED%20)

**Comment by zoffixznet** [comment]
Yes, at https://docs.perl6.org/programs/00-running

OK. We not gonna keep `$*MAIN-ALLOW-NAMED-ANYWHERE`. It'll be some hash instead.

I'll implement the hash tonight and spec and document it.

**Comment by bduggan** [comment]
Cool!  I've updated my slides (and linked to them from the youtube page) with information about this syntax: http://bduggan.github.io/meta-perl6-cli/index.html#27

**Comment by zoffixznet** [comment]
> Cool! I've updated my slides 

After a discussion, there was another minor change in that the hash is not declared by default (keeps the startup leaner), so you need to `my` it, e.g. like this:

```
my %*SUB-MAIN-OPTS = :named-anywhere;
```

**Comment by bduggan** [comment]
Got it.  Changed.

**Pull request closed without merging**
