### PR TITLE
change else-if to given/when switch

### PR DESCRIPTION
**Pull request by WildYorkies**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Feels pointless to alias to $contents just to immediately use `given` to alias it to $_ you would have had with `for` by default

**Comment by WildYorkies** [comment]
Can you combine given and for?

```perl6
given for @items {
  when Str { $_ }
  when Positional { $_ }
}
```

Just trying to make the original code more readable.

**Comment by b2gills** [comment]
All `given` does is temporarily store its argument in `$_`, which `for` also does by default.

**Comment by b2gills** [comment]
Also you didn't need to add the parameter to the `$_.map: ...`

And you could do the same improvement to that inner mapped block

And you can do an implicit `map` method call ( not that it makes it any clearer )

    when Positional {
        @chunks.append: .map: {
            when Pod::Block {
                *.&pod-gist
            }
            when Str {
                $_
            }
        }
    }

**Comment by WildYorkies** [comment]
The code needs help.

If the item is a Pod::Block, it recurses. The rest of the patterns should follow that example.

`sub pod-gist` should be a multi that accepts either a Pod::Block, Str, or Positional.

**Comment by b2gills** [comment]
That could lead to a cleaner implementation

**Pull request closed without merging**
