### PR TITLE
Coke/examples

### PR DESCRIPTION
**Pull request by coke**
For #1194 

This is not yet intended to be merged, but to be considered for review.

Runtime for this test is definitely slower than before, but the output in case of failure is much more helpful.

The slowness is because this branch removes the caching of a combined example per test file, using instead a precompiled version of the source (same mechanism used by htmlify) and walking over that each time the test is run. We can add a similar kind (but more complicated given the split into chunks) of caching back if needed.

### CODE REVIEW

**Comment by Altai-man** [comment]
Let's see. In general, I like your solution, but the performance is concerning me. On my machine timing for an old variant is
```
214.27user 8.74system 3:46.54elapsed 98%CPU (0avgtext+0avgdata 850816maxresident)k
0inputs+0outputs (2major+4330917minor)pagefaults 0swaps
```
and
```
695.34user 97.95system 13:20.38elapsed 99%CPU (0avgtext+0avgdata 611648maxresident)k
0inputs+0outputs (0major+44129286minor)pagefaults 0swaps
```
for a new.

I wonder, can we improve it with concurrency? We can run examples from a single file in batches of some size concurrently and afterwards concatenate the results in a correct order. Should I try it?

With `hyper` added on last function the results on my machine is
```
1079.25user 137.64system 5:56.23elapsed 341%CPU (0avgtext+0avgdata 774800maxresident)k
0inputs+0outputs (0major+44239988minor)pagefaults 0swaps
```

Also, we should count tests from 1, not from zero, I suppose.

**Comment by coke** [comment]
In general, my preference is to not add concurrency to the individual tests, since we are managing that at the test file level with prove -j / TEST_JOBS

**Comment by Altai-man** [comment]
In this case, I have no objections against this changes. :+1:

**Comment by coke** [comment]
New version using EVAL (with a different wrapper script to avoid executing as much as possible) instead of 'perl6 -c' - much faster; I think the previous version was not running the code but was running the code "True" each time; So the current version has some test failures (need to at least be passing the test before merge.)

**Comment by coke** [comment]
Fixed - I missed the pod formatting code support on the initial version (because I wasn't actually running the example code!). Now passes all tests and is very fast.

**Comment by coke** [comment]
TImings with the latest on master and coke/example:

master: 

real	1m27.413s
user	1m13.813s
sys	0m6.849s

branch: 

real	0m28.238s
user	0m25.326s
sys	0m1.414s

**Comment by coke** [comment]
I'm OK if this gets merged now.

**Pull request merged**
