### PR TITLE
Update modules.pod to suggest Travis-CI integration.

### PR DESCRIPTION
**Pull request by zaucker**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Just curious, why do you link some repo and not the [Travis Perl 6 setup docs](https://docs.travis-ci.com/user/languages/perl6)? If that repo offers a much better setup, we should update Travis docs instead.

:-1: from me on this PR

**Comment by zaucker** [comment]
@zoffixznet: because I discovered the "Travis Perl 6 setup docs" just before you sent your comment and because  http://modules.perl6.org/ links to that repo (Travis link in the second sentence). I guess that should be fixed too ... I'll submit yet another PR.

**Comment by zoffixznet** [comment]
@zaucker thanks for spotting modules.perl6.org thing. Yes, I think that should also link to the docs on Travis. I know who ugexe is, but googling "perl 6 travis" leads me to the Travis docs, not ugexe's repo. Thus, the docs should be updates with whatever extra benefit's ugexe's version provides (I see it offers stack traces as well as sends reports to panda testers). The PR for the docs can be made against this: https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/perl6.md

**Comment by zaucker** [comment]
Just submitted the PR on the moduels.perl6.org line.

I agree that ugexe's version should have more documentation.  His  example
.travis.yml file actually didn't work for a module I was trying to integrate
into Travis (might have been my fault).

I also noticed that the .travis.yml files of various modules in th
modules.perl6.org list have more or less different from each other. I think
a default .travis.yml for "simple cases" might really be useful and could
perhaps be integrated into the https://docs.travis-ci.com/user/languages/perl6
page.

I am not sure if this is useful, but I thought that I could create PRs for
modules on the list that are not set up for Travis yet.  At least for those
which I am trying out or using.

Cheers,
Fritz

On Thu, 14 Jan 2016, Zoffix Znet wrote:

> @zaucker thanks for spotting modules.perl6.org thing.  Yes, I think that
> should also link to the docs on Travis.  I know who ugexe is, but googling
> "perl 6 travis" leads me to the Travis docs, not ugexe's repo.  Thus, the
> docs should be updates with whatever extra benefit's ugexe's version
> provides (I see it offers stack traces as well as sends reports to panda
> testers).  The PR for the docs can be made against this:
> https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/languages/perl6.md
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/perl6/doc/pull/349#issuecomment-171643540

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by zoffixznet** [comment]
> I am not sure if this is useful, but I thought that I could create PRs for modules on the list that are not set up for Travis yet. At least for those which I am trying out or using.

That's definitely useful as it allows the potential users of a module to see whether it works at all. Be sure to mention to the authors that along with adding the .travis.yml file, they also need to go to `https://travis-ci.org/profile/THEIR_GITHUB_USERNAME` and enable the repo there.

**Comment by zaucker** [comment]
On Thu, 14 Jan 2016, Zoffix Znet wrote:

>> I am not sure if this is useful, but I thought that I could create PRs
>> for modules on the list that are not set up for Travis yet.  At least for
>> those which I am trying out or using.
>
> That's definitely useful as it allows the potential users of a module to
> see whether it works at all.

That was the idea ...  I guess ultimately it might be useful to require that
before putting a module on the list.  It's not such a big deal after all ...

> Be sure to mention to the authors that along with adding the .travis.yml
> file, they also need to go to
> `https://travis-ci.org/profile/THEIR_GITHUB_USERNAME` and enable the repo
> there.

Good point, thanks.

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Pull request closed without merging**
