### PR TITLE
Remove vim settings bits from a number of documents.

### PR DESCRIPTION
**Pull request by djgoku**
I found the issue by seeing `*.pod` files being broken in github. Remove all instances I could find.

### CODE REVIEW

**Comment by moritz** [comment]
The modelines are there for a reason; rejecting.

(Also pod being broken on github is a symptom of github not rendering Perl 6 pod, not of the modeliness)

**Comment by djgoku** [comment]
Can you point me to a document the reasoning/explanation?

If they are supposed to be there, is there a reason it isn't present on every file?

Jonathan Otsuka

**Comment by moritz** [comment]
It's not documented. It's simply handy that every contributor (at least those using vim) uses the same editor settings.

And it's not in every file because we haven't bothered to automate it.

**Comment by paultcochrane** [comment]
Would it be generally worthwhile to automate it?  If so, I could add a check for the appropriate modelines and add them where necessary.

**Comment by zoffixznet** [comment]
Broken `.pod`s are unrelated to vim files (See #167)

**Comment by djgoku** [comment]
Could we not add a recommended vimrc file with all the settings and point people to it?

**Comment by FROGGS** [comment]
How do you do that? And how nice will that play with ppl jumping between projects?

For example we added the vimlines to the core setting files to not let hard tabs sneak into our codebase. Even when I'm not using vim, I understand that we want to keep them.

**Comment by djgoku** [comment]
I don't use vim so I can't relate. I use the defaults for vi, sublime text and atom.

**Comment by moritz** [comment]
What's the big issue here? Why can't we just keep the status quo? What's the problem?

**Comment by jonathanstowe** [comment]
There isn't one.  In any other text editor the modeline is just a comment, if something is attempting to parse the file and getting confused by a comment then that thing is broken not the document.

**Comment by zoffixznet** [comment]
Reading the discussion, I think this was left un answered:

> moritz: And it's not in every file because we haven't bothered to automate it.

> paultcochrane: Would it be generally worthwhile to automate it? If so, I could add a check for the appropriate modelines and add them where necessary.

**Comment by jonathanstowe** [comment]
So I'd say :+1: to @paultcochrane's suggestion :)

**Pull request closed without merging**
