### PR TITLE
Add ^ twigil to traps. Fixes #364

### LINKED ISSUE #364: List $^placeholders as one of the traps
http://doc.perl6.org/language/variables#The_^_Twigil

> Although it is possible to use nearly any valid identifier as a placeholder variable, it's recommended to use short names or ones that can be trivially understood in the correct order, to avoid surprise on behalf of the reader.

In other words, some people may be tempted to have meaningful placeholder names while expecting it to work in the order of appearance. This is definitely a potential [trap](https://doc.perl6.org/language/traps).

### PR DESCRIPTION
**Pull request by nicqrocks**
This adds some explanation as to how the ^ twigil placeholder variables work and how some people can run into troubles with them.

### CODE REVIEW

**Comment by nicqrocks** [comment]
Does it look like it needs anything or has something left out?

**Comment by MasterDuke17** [comment]
The travis complaint is about tabs, and the rest of docs don't rely on line-wrapping, but the actual content looks good.

**Comment by b2gills** [comment]
The `^8` should be changed to something else so that a new Perl 6 programmer is less likely to get confused

( It initially confused [\[Coke\]](https://irclog.perlgeek.de/perl6/2016-10-11#i_13378023) for example )

**Comment by coke** [comment]
(confusing) specifically, using the up to prefix operator (^) when we're already talking about the ^ twigil.

**Comment by AlexDaniel** [comment]
Just change it to ``1..4``.

**Comment by AlexDaniel** [comment]
Ah. Oops, there are two instances of using the range operator. Yeah… don't know about the first one. ``0..7`` anyone?

**Comment by nicqrocks** [comment]
Yeah, I was thinking about that myself. I think 0..7 (and similar) would be a good change.

**Comment by nicqrocks** [comment]
Ok, that should be good. Can you guys think of anything else?

**Comment by AlexDaniel** [comment]
It's good. But:

> The trouble arises when a person wants to use more complex names for the variables.

``$^first`` and ``$^second`` are already too complex. I don't think that anything besides 1 character name is justified.

What about demonstrating the right example instead?

It will read like this:

```
Using the C<^> twigil can save a fair amount of time and space when writing out small blocks of code. As an example:

	for 0..7 -> $a, $b { say $a + $b; }

can be shortened to just

	for 0..7 { say $^a + $^b; }

The trouble arises when a person wants to use more complex names for the variables.

…
```

**Comment by AlexDaniel** [comment]
Also, consider using ``1..4`` instead of ``0..3``. It will correspond to ``$^one $^two $^three $^four`` variables better.

**Comment by AlexDaniel** [comment]
Well the output has to be changed as well then: ``# 1 3 2 0`` → ``# 2 4 3 1``.

Also, please replace tabs with spaces (so that travis does not complain).


Other than that it is mergeable.

**Comment by nicqrocks** [comment]
Ok 👌

**Comment by tommystanton** [comment]
@nicqrocks (@MasterDuke17, @AlexDaniel): If you have [Ack installed](http://beyondgrep.com/install/), you can find out where the tabs are by running:

```text
$ ack '\t' doc/Language/traps.pod6
```

**Comment by AlexDaniel** [comment]
@coke perhaps [``tabs.t``](https://github.com/perl6/doc/blob/master/t/tabs.t#L20) should also mention line numbers?
… or maybe it should even fix it itself when run with some env variable (``FIX_WHITESPACE`` ?).

Personally I have no issues with any of that, as I am able to configure any text editor to display whitespace. But a more helpful ``tabs.t`` could help contributors a lot, I think.

**Comment by AlexDaniel** [comment]
I think you did a great job.

There are other tickets related to traps: #602 #959 #960, perhaps consider working on these too.

**Comment by nicqrocks** [comment]
Sure, I'll take a look! 😃

**Pull request merged**
