### PR TITLE
Mostly whitespace/syntax cleanup

### PR DESCRIPTION
**Pull request by MasterDuke17**
One or two actual changes to code, but no operational changes.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
It is great. But this:
```diff
-my $total-found = [+] %found.values.map( *.elems );
+my $total-found = %found.values.map( +* ).sum;
```
is more like code obfuscation. ``.sum`` is fine, but ``+*`` instead of ``*.elems`` is probably not a good idea. I think that it is worth changing it back to ``*.elems``.

**Comment by MasterDuke17** [comment]
Yeah. I think I was trying to make it consistent with the rest of the code, but it looks like a roughly even split between `+<array_goes_here>` and `<array_goes_here>.elems`. Feel free to make that change, unless you'd rather I do it?

**Comment by zoffixznet** [comment]
Rather you do it :) The documentation may be perused by novices so it's best to avoid clever code, even if it is more concise.

**Comment by MasterDuke17** [comment]
That was ugly, but things seem ok now.

**Comment by jonathanstowe** [comment]
Thanks!

**Pull request merged**
