### PR TITLE
Mention importance of closing handles in 5to6

### PR DESCRIPTION
**Pull request by rafaelschipiura**
#1536

### CODE REVIEW

**Comment by zoffixznet** [comment]
Personally, I wouldn't mention the `LEAVE` phaser here. If someone's reading 5to6 docs, it'd be unfamiliar territory, and `LEAVE` has caveats, such as still being called even when a routine is called with wrong args.

Perhaps the prose here should just refer to https://docs.perl6.org/type/IO::Handle#routine_close for various ways of closing handles?

**Comment by rafaelschipiura** [comment]
Just putting C<close> is enough?

**Comment by zoffixznet** [comment]
> Just putting C is enough?

`C<>` just styles it as code. You need `L<close>` to make it a link to close routine.

**Comment by zoffixznet** [comment]
👍 Thanks!

**Pull request merged**
