### PR TITLE
add (passing) trailing whitespace test

### PR DESCRIPTION
**Pull request by coke**
branched from the tab-test branch. Adds a new test file to check for trailing whitespace.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I think that we should give it a try. If nobody is going to say something against this then I'll work on merging this in the next few days.

**Comment by coke** [comment]
All tests should pass now, also merged in all changes from master as of a minute ago.

**Comment by jonathanstowe** [comment]
Is there any reason not to merge this?  It looks fine.

**Comment by AlexDaniel** [comment]
@jonathanstowe no and yes. There are people who think that trailing whitespace is irrelevant, and therefore we should just ignore it. Such tests do exactly the opposite (it makes CI systems scream when the issue is not that big).

For that reason it was a good idea to give it a little bit of time, just to see if somebody has to say something about it. Since nobody did, you are right, there's no reason not to merge it.

``tws-test`` branch is now merged into master. This pull request was about merging it into ``tab-test``, but that is not very meaningful, so I am closing this.

**Pull request closed without merging**
