### PR TITLE
README example needs PERL6LIB to be set

### PR DESCRIPTION
**Pull request by bduggan**
Hi,

The first example in the README wasn't working for me (rakudo 2016.06).  Setting PERL6LIB seems to fix it.

best
Brian

### CODE REVIEW

**Comment by coke** [comment]
It works as is for me. What does

```
perl6 -v
```

say for you?

**Comment by zoffixznet** [comment]
Also, would you, please, include any error messages you receive?

**Comment by bduggan** [comment]
```
bduggan: perl6 -v
This is Rakudo version 2016.06 built on MoarVM version 2016.06
implementing Perl 6.c.
```
Also:
```
bduggan: uname -a
Linux minty 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
bduggan:
```

**Comment by bduggan** [comment]
I added PERL6LIB since the docs weren't in this list of directories (from `search-paths()`)
```
bduggan: perl6 -e '.say for $*REPO.repo-chain X~ </doc/>'
/home/bduggan/.perl6/doc/
/home/bduggan/.rakudobrew/moar-2016.06/install/share/perl6/site/doc/
/home/bduggan/.rakudobrew/moar-2016.06/install/share/perl6/vendor/doc/
/home/bduggan/.rakudobrew/moar-2016.06/install/share/perl6/doc/
CompUnit::Repository::AbsolutePath<82077344>/doc/
CompUnit::Repository::NQP<70206632>/doc/
CompUnit::Repository::Perl5<70206672>/doc/
```

**Comment by coke** [comment]
Updated my local copy to 2016.07.1, now having a similar problem:

```
$ ./bin/p6doc Type::Str
===SORRY!===
Could not find JSON::Fast at line 3 in:
    /Users/williamcoleda/.perl6
    /Users/williamcoleda/.rakudobrew/moar-2016.07.1/install/share/perl6/site
    /Users/williamcoleda/.rakudobrew/moar-2016.07.1/install/share/perl6/vendor
    /Users/williamcoleda/.rakudobrew/moar-2016.07.1/install/share/perl6
    CompUnit::Repository::AbsolutePath<140722530704352>
    CompUnit::Repository::NQP<140722525912640>
    CompUnit::Repository::Perl5<140722525912680>
```

**Comment by coke** [comment]
I just updated my local perl6 to 2016.07.1, and after installing panda (which comes with JSON::Fast), I still don't have this problem - no PERL6LIB needed.

**Comment by Altai-man** [comment]
Yes, it works for me too.
```
➜  doc git:(master) ✗ ./bin/p6doc Type::Str
Could not find Type::Str at line 0 in:
    /home/sena/.perl6
    /home/sena/.rakudobrew/moar-nom/install/share/perl6/site
    /home/sena/.rakudobrew/moar-nom/install/share/perl6/vendor
    /home/sena/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<52999664>
    CompUnit::Repository::NQP<52202064>
    CompUnit::Repository::Perl5<52202104>
  in sub old-locate-curli-module at ./bin/p6doc line 218
  in sub locate-module at ./bin/p6doc line 39
  in sub MAIN at ./bin/p6doc line 92
  in block <unit> at ./bin/p6doc line 237
➜  doc git:(master) ✗ perl6 -v
This is Rakudo version 2016.06-232-gc7332c0 built on MoarVM version 2016.06-9-g8fc21d5
implementing Perl 6.c.
```
But
```
PERL6LIB=. ./bin/p6doc Type::Str
```
opens page without error.

**Comment by bduggan** [comment]
Sorry -- here's the original error message I saw (before adding PERL6LIB):
```
./bin/p6doc Type::Str
Could not find Type::Str at line 0 in:
    /home/bduggan/.perl6
    /home/bduggan/.rakudobrew/moar-2016.06/install/share/perl6/site
    /home/bduggan/.rakudobrew/moar-2016.06/install/share/perl6/vendor
    /home/bduggan/.rakudobrew/moar-2016.06/install/share/perl6
    CompUnit::Repository::AbsolutePath<58072512>
    CompUnit::Repository::NQP<57980688>
    CompUnit::Repository::Perl5<57980728>
  in sub old-locate-curli-module at ./bin/p6doc line 218
  in sub locate-module at ./bin/p6doc line 39
  in sub MAIN at ./bin/p6doc line 92
  in block <unit> at ./bin/p6doc line 237

```

**Comment by bduggan** [comment]
I was able to reproduce this issue in travis:
https://travis-ci.org/bduggan/doc/builds/145605107
https://github.com/bduggan/doc/blob/readme-example-with-failing-test/t/p6doc.t

**Comment by bduggan** [comment]
@coke -- is there some extra configuration that should be provided?  (or does the docs/ directory need to be copied somewhere?)  The [travis example](https://travis-ci.org/bduggan/doc/builds/145605107)  shows the issue occurring even for version `2016.07.1-1-g18455a5`.

**Comment by coke** [comment]
No extra config here, works fine out of the box. I'm on OSX:

```
$ git clean -xdf
$ git pull --rebase
$ git rev-parse --short HEAD
4eafbfe
$ env | grep -i perl6lib
$ ./bin/p6doc Type::Str
TITLE
class Str
...
```

**Comment by zoffixznet** [comment]
I'm experiencing the same issue, as OP. @coke What's in your `PERL6LIB` (or whatever other method there is for setting `lib`)? Perhaps you added `.` into it globally.

```
zoffix@leliana:~$ t
zoffix@leliana:/tmp/tmp.xm1fy2IE9D$ echo $PERL6LIB

zoffix@leliana:/tmp/tmp.xm1fy2IE9D$ git clone https://github.com/perl6/doc
Cloning into 'doc'...
remote: Counting objects: 19812, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 19812 (delta 31), reused 0 (delta 0), pack-reused 19760
Receiving objects: 100% (19812/19812), 4.90 MiB | 0 bytes/s, done.
Resolving deltas: 100% (13146/13146), done.
Checking connectivity... done.
zoffix@leliana:/tmp/tmp.xm1fy2IE9D$ cd doc/
zoffix@leliana:/tmp/tmp.xm1fy2IE9D/doc$ ./bin/p6doc Type::Str
Could not find Type::Str at line 0 in:
    /home/zoffix/.perl6
    /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site
    /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/vendor
    /home/zoffix/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<73660112>
    CompUnit::Repository::NQP<73269440>
    CompUnit::Repository::Perl5<73269480>
  in sub locate-curli-module at ./bin/p6doc line 218
  in sub locate-module at ./bin/p6doc line 39
  in sub MAIN at ./bin/p6doc line 92
  in block <unit> at ./bin/p6doc line 225

zoffix@leliana:/tmp/tmp.xm1fy2IE9D/doc$ 
```

**Comment by coke** [comment]
See my comment, where I dump my env and look for Perl6lib - it's empty.

**Comment by coke** [comment]
P6DOC_DEBUG=1 ./bin/p6doc Type::Str

This is showing a bunch of candidate directories that are in no way tied to the perl6 I'm running.

**Comment by coke** [comment]
```
$ perl6 -e '$*REPO.repo-chain()>>.Str.say'
```

^^ for me this is quite noisy (and has nothing to do with the perl6 I'm using). Zoffix reports on irc that it's empty for him. This is the source of the discrepancy here.

**Comment by zoffixznet** [comment]
To clarify, it's the `($*REPO.repo-chain()>>.Str X~ </doc/>).grep: *.IO.d` used in `p6doc` that gives me empty list. `$ perl6 -e '$*REPO.repo-chain()>>.Str.say'` just gives me the regular locations for modules, of which `.` isn't a part of.

Also, to add a comment on the PR itself. This issue should be resolved by adding `use lib <.>` to `p6doc` or something similar, rather than asking users to specify env vars on command line.

**Comment by bduggan** [comment]
How about this change?  (adds . to the list of dirs in repo-chain)

**Comment by zoffixznet** [comment]
> How about this change? (adds . to the list of dirs in repo-chain)

Needs a Slip in there or it'll take all the `$*REPO` paths as one thing: 

```
zoffix@leliana:~$ perl6 -e '(".", $*REPO.repo-chain())>>.Str.elems.say'
2
zoffix@leliana:~$ perl6 -e '(".", |$*REPO.repo-chain())>>.Str.elems.say'
8
zoffix@leliana:~$ 
```

**Comment by bduggan** [comment]
Oh, cool, thanks.

**Comment by zoffixznet** [comment]
Since Travis and three users have this issue, I'm going to merge the fix.

I'm not sure why everything works on Coke's machine, but since he reports $*REPO.repo-chain printing stuff for a completely different perl6, then I feel that's a separate issue outside the scope of this PR.

**Pull request merged**
