### PR TITLE
Update META6.json documentation to include "api" field

### PR DESCRIPTION
**Pull request by Tyil**
I'm considering to split up this section into a mandatory and optional section, to make it clearer what a user *needs*, and what they can additionally use to achieve certain goals (such as semantic versioning, in this case).

### CODE REVIEW

**Comment by MARTIMM** [comment]
I was wondering how the user of a dependency has to select the proper version when there is a version and an api? How should zef process it ?

**Comment by Tyil** [comment]
You can use `Module:ver<1.2.3>:api<1>` to select both. You can also leave off the `:api` if you don't care about that one, just like how you can leave out the `:ver` part.

In the `depends` field, the following are all correct:
- `Module` - Just give me Module, I don't care which version or API
- `Module:ver<1.0.0+>` - Give me Module, at least version 1.0.0
- `Module:api<1>` - Give me Module with API 1, no matter which version implements that API
- `Module:ver<1.0.0+>:api<1>` - Give me Module with at least version 1.0.0, but only if it also implements API 1

**Comment by MARTIMM** [comment]
Thank you for the explanation.
The api field is optional so when I use Module:api<1>, zef has to devise that from its version. Is that correct? Then, when I read the docs about it, it would not give the newest version if The dependency would get version 2.0.0. That is nice! 
Regards,
Marcel

**Comment by Tyil** [comment]
I'm not sure what `zef` will do if you specify a `Module:api<1>` as a dependency, but the dependency has no `api` field in its `META6.json`. Maybe @ugexe can expand on that.

**Comment by ugexe** [comment]
`Foo:api<1>` is the same as `Foo:api<1>:ver<*>`. `Foo` is the same as `Foo:api<*>`

`@meta-data.sort({ Version.new($_<api>) }).sort({ Version.new($_<ver>) })`

If no `api` field is found in the META6 then it will be treated as 0 / * ( just like a `ver` that is declared as `*` ). It will not be guessed from the `ver` field.

**Comment by JJ** [comment]
Related: #551. Maybe close it. I'll have to check.

**Pull request merged**
