### PR TITLE
Style cleanup.

### PR DESCRIPTION
**Pull request by antquinonez**
Please use whatever you like. Thanks.

I closed the other pull requests since there was an issue with rebasing.

### CODE REVIEW

**Comment by Altai-man** [comment]
It seems good for me, +1 for merging.

**Comment by jonathanstowe** [comment]
Go for it

**Comment by samcv** [comment]
Will get to this sometime today. Most looks fine. Thanks.

**Comment by coke** [comment]
In future, lets make sure merges like this pass 'make xtest' - several new failures here.

**Pull request merged**
