### PR TITLE
Replace instances of Perl 6 with Raku and more

### PR DESCRIPTION
**Pull request by uzluisf**
* Perl 6 -> Raku
* perl6 -> raku
* .p6 -> raku
* .pod -> rakudoc
* .pm6 -> rakumod
* Variables containing PERL6/PERL ($*PERL6 -> $*RAKU, etc.)

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I'll close this to make sure nobody merges it ahead of time.

You can't change extensions because no tools support them yet. You can't change env vars for the same reason. You can't change emails because I don't believe there's forwarding set up already. You can't change the executable because most distro packages don't have raku executable.

All that will be possible soon, but not now. We have to fix the tooling first, and the changes in documentation will follow. It has been 1 day since the rename, so of course most raku pieces are not in place yet.

**Comment by AlexDaniel** [comment]
Feel free to resubmit with just the plaintext changes (“Raku compiler”, “rakuish”, etc.)

**Comment by JJ** [comment]
There's a roadmap here #3046 . I would really be grateful if we stuck to it. @AlexDaniel is right, for the time being just *the name of the language* has changed, and there's issue #3056 to solve that. Revising what has been done there, and finding other instances that haven't been substituted automatically is, for the time being, the next step.

**Comment by uzluisf** [comment]
Sorry I couldn't get back to you earlier and you're totally right. I got a bit carried away 😅.

**Comment by JJ** [comment]
@uzluisf thanks anyway, I appreciate the effort :+1:

**Pull request closed without merging**
